---
# tasks file for sshd
- name: Copy sshd config
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/ssh/sshd.config.d/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  loop:
    - 90-root-login.conf
  notify: Restart sshd
